default: &default
  adapter: postgresql
  encoding: unicode
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  host: <%= ENV['POSTGRES_HOST'] %>
  pool: 5
  timeout: 5000

development:
  #<<: *default
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
  #database: <%= ENV['POSTGRES_DB'] %>

test:
  #<<: *default
  adapter: sqlite3
  database: db/test.sqlite3
  pool: 5
  timeout: 5000
  #database: <%= ENV['POSTGRES_TEST_DB'] %>

production:
  <<: *default
  database: <%= ENV['POSTGRES_DB'] %>
